### ISSUE TITLE
Incomplete code for your model

### ISSUE THREAD

**Issue by ImKeTT** [Derekkk/Mocha-EMNLP22#2]
Great work and thanks for sharing the code. 

However, it seems that you only provide codes for T5 (few-shot) fine-tuning, or your MOCHA model with only end-to-end generation trianing task. Looks like no training code for the rest two training tasks here. 

It would be really great if you could release the full model trianing/inference code and more detailed instructions for using the model. Thanks a lot!

**Comment by Derekkk** [comment]
Hi Haoqin,

Thanks for the interests. We convert all tasks to text-to-text transfer, so that they share the same model training code and the difference comes from the data. If you take a look at the processed data, the "task" key in each json list represents the corresponding task. We control what tasks to be included during training in data processing (e.g., line 144 in finetune_generation_pipeline.py). Plz let me know if there's any questions.

**Comment by ImKeTT** [comment]
oh, I see. Thank you very much for your reply and explanation. And again, this is an awesome work and thanks for sharing the code with us.
